### ISSUE TITLE
star.py limit number star before posting

### ISSUE THREAD

**Issue by Note2Self** [TrustyJAID/Trusty-cogs#1]
Hi is there a way I can set a limit before posting to the starboard channel. For example the post should receive 3 stars minimum before it gets posted to starboard channel.

**Comment by KevinRodal** [comment]
I actually have this same request. @TrustyJAID I can go in and do this myself and submit a merge request if you'd like?

**Comment by TrustyJAID** [comment]
I'll take a quick look to see if I can add this easily now. I was working on being able to set multiple emoji and channels for the starboard that I would also like to implement.

**Comment by TrustyJAID** [comment]
Added a threshold ability to this cog. You'll have to set the threshold to something before the starboard will work.
