### ISSUE TITLE
Imgflip - Number of lines

### ISSUE THREAD

**Issue by MK99MA** [TrustyJAID/Trusty-cogs#16]
I'm glad you recreated this cog for Red V3, however a flaw from V2 still persists. It is still only possible to commit 2 lines per query, rendering certain templates useless as they require 3 or more inputs for their proper use.
Seeing that the imgflip API allows the usage of _boxes_ instead of _text0_ & _text1_ for templates with more than 2 textboxes I was wondering if it is somehow possible for Red to use more than 2 inputs too.

Of course this "Issue" is not urgent at all.

**Comment by TrustyJAID** [comment]
That is a limitation of the API itself. There is only 2 lines you can input and I do not see a good easy to explain way of allowing user defined box settings through discord to access that option.

**Comment by MK99MA** [comment]
First of all, thanks for the fast reply.
My knowledge regarding their API and especially the possibilites of Discord.py etc is pretty limited, however with them stating on their API site (https://api.imgflip.com/): 


> If you do not specify bounding box coordinates, the same automatic default coordinates from imgflip.com/memegenerator will be used, which is very useful for memes with special text box positioning other than the simple top/bottom.

I thought the need of passing user defined boxes is not necessary and only commiting 1 to 5 lines of text would be enough, ignoring possible coordinates or edits regarding the bounding box.

I'm sorry if I just didn't understand the issue explained in your reply, to me their description just sounds like _boxes_ will use the same default boundaries and coordinates of the template if nothing else is declared.

**Comment by TrustyJAID** [comment]
Thanks for pointing that out, I completely missed it. Solved in 8fad591!
