### ISSUE TITLE
[InviteBlocklist] Suggestion for channel allowlist.

### ISSUE THREAD

**Issue by Fabian-Evolved** [TrustyJAID/Trusty-cogs#161]
Not sure if the way to cog is, is intended for just guilds only.

Anyways i would love to be able to block invites across the guild, however have 1 channel on the guild be dedicated that i would allow people to post Discord invites.

like for example having 1 channel dedicated to being a sort of promote yourself channel. and that the cog would remove the invites from any other channels that aren't listed for invites to be allowed on.

I hope this made sense.
If not let me know what you didn't understand and i'll try to revisit my explenation.

Thanks for you time, i love the cog!

**Comment by TrustyJAID** [comment]
I've started working on adding this feature over a week ago but am currently stuck figuring out how to have it make sense. Ideally it would be two separate blacklists/allowlists for users, channels, and roles the same as I have in other cogs. But the command structure is giving me some grief. Do I allow blacklisting channels users and roles from the same command? Or do I make another command that is different? I'll try taking another crack at it today.

**Comment by TrustyJAID** [comment]
This has been addressed in #168
