### ISSUE TITLE
enable pings for tweet posts

### ISSUE THREAD

**Issue by entchen66** [TrustyJAID/Trusty-cogs#162]
Hey Trusty,
is it possible to enable it that the bot can also ping roles while posting a tweet?
It gets changed with new dpy version.

Greetings Fox

**Comment by TrustyJAID** [comment]
I personally do not see a point in building this into the cog itself. However, all tweets are dispatched as an event in the bot under `on_tweet_status` so you can simply create another cog that can scan for specific tweets and mention whomever you like.
