### ISSUE TITLE
Welcome COG: Avatar

### ISSUE THREAD

**Issue by AlphaOmega2020** [TrustyJAID/Trusty-cogs#182]
**Is your feature request related to a problem? Please describe.**
No Problem

**Describe the solution you'd like**
To enhance the welcome cog to display the users Avatar

**Describe alternatives you've considered**
None

**Additional context**
![welcome](https://user-images.githubusercontent.com/59516621/97018429-0d9a2800-1547-11eb-94ca-a5a461e97136.png)

**Comment by TrustyJAID** [comment]
This is already possible by doing `[p]welcomeset embed image greeting member`
