### ISSUE TITLE
[RoleTools] Improve help messages for commands using `RoleEmojiConverter`

### ISSUE THREAD

**Issue by Jackenmen** [TrustyJAID/Trusty-cogs#188]
> `[role_emoji...]` Must be a role followed by the emoji tied to that role

This is not enough information to know what I'm supposed to pass. My first thought was that "followed by" will mean that emoji should be sent after space, but that is not the case. I would suggest to at least say what separator they should use, but I think that preferably the command should also include an example usage, especially when it comes to role names with spaces.

**Comment by TrustyJAID** [comment]
This has been addressed in b7190e29006b8ad64899941a24294a25e2e863ba.
