### ISSUE TITLE
[RoleTools] Exclusive Role Support

### ISSUE THREAD

**Issue by ann4belle** [TrustyJAID/Trusty-cogs#191]
**Is your feature request related to a problem? Please describe.**
I help moderate multiple servers with roles that should be exclusive to one or more other roles.

**Describe the solution you'd like**
Ideally, a way to add role groups, where only one role out of the group can be applied to any given user at one time.

**Describe alternatives you've considered**
There doesn't seem to be a V3 cog out there that does something like this. The closest I can find allows two roles to be mutually exclusive, but I'd rather not try to hack together a solution for 3+ roles all being mutually exclusive.

**Comment by Jacob-1999** [comment]
This has been added as of yesterday. Ref [84fbb0f](https://github.com/TrustyJAID/Trusty-cogs/commit/84fbb0fe33d2f53209fd7fcb1733e3673e103b64)
