### ISSUE TITLE
[Retrigger] Allowlist channel and role cannot be used at the same time.

### ISSUE THREAD

**Issue by Skyridr** [TrustyJAID/Trusty-cogs#209]
If you set up a retrigger and add a channel and a role to the allowlist, the allowlist is ignoring the role set up and triggers by all roles regardless.

![image](https://user-images.githubusercontent.com/6794064/106635268-ee1c8d80-6580-11eb-95a2-3f4abfaa9940.png)

The channel in the allowlist still seems to work however. If I remove the channel from the allowlist and leave the role alone, the role set in allowlist works nicely. But they cannot be used at the same time.

**Comment by TrustyJAID** [comment]
This is working as intended. The Allowlist tells the bot what channels, users, or roles are *allowed* to run the trigger whereas the blocklist tells the bot which channels, users, or roles are not allowed to run the trigger.
