### ISSUE TITLE
[AddImage] Unable to delete a single global command

### ISSUE THREAD

**Issue by madebylydia** [TrustyJAID/Trusty-cogs#215]
**Describe the bug**
By looking at the `[p]addimage` command, there is no subcommands for deleting a global command if we created one through `[p]addimage addglobal`

**To Reproduce**
1. Create a global command using addimage.
2. Try to delete it without affecting other images.

**Expected behavior**
Ability to delete one command inly, not every commands.

**Comment by TrustyJAID** [comment]
Unfortunately this command is hidden and I cannot remember why. Use `[p]addimage deleteglobal`.
