### ISSUE TITLE
[Welcome] Wrong image when inviting a bot

### ISSUE THREAD

**Issue by madebylydia** [TrustyJAID/Trusty-cogs#216]
**Describe the bug**
This bug consist of setting up an image in a embed and invite a bot, resulting of sending the wrong image.

**To Reproduce**
1. Enable greeting welcome on bot 1
2. Enable embed
3. Set one image for joining and one image for leaving
4. Invite bot 2

**Expected behavior**
Bot 1 should send the image that was set for joining, but it use the image set for leaving.

**Comment by TrustyJAID** [comment]
The Welcome cog at this time only has 1 setting for embeds that is the same for both welcomes and greetings. Images are therefore the same for both so your setting for leaving and joining are the one that was set last.
