### ISSUE TITLE
[Cleverbot] Creating instance with cleverbot.io fails

### ISSUE THREAD

**Issue by monospacedmagic** [TrustyJAID/Trusty-cogs#24]
After creating an account on cleverbot.io, I set the API user and key using `[p]cleverbotset ioapikey <api_user> <api_key>`. However, when I try to query the API using e.g. `[p]cleverbot Hi!`, the bot keeps typing for about a minute and then responds with the following message:

```
Error contacting the API. Error code: Error making instance: 524
```

Resetting the API credentials didn't help (yes, I set them using `[p]cleverbotset ioapikey <api_user> <api_key>` after resetting them on cleverbot.io). This issue has occured to at least one other user as well, as it has been reported on Discord two days ago by someone else already.

**Comment by TrustyJAID** [comment]
This is an error on the cleverbot.io side, nothing I can really do to fix it.
