### ISSUE TITLE
NotSoBot watermark booms

### ISSUE THREAD

**Issue by designbyadrian** [TrustyJAID/Trusty-cogs#25]
EXCEPTION IN (/home/designbyadrian/.local/share/Red-DiscordBot/cogs/CogManager/cogs/notsobot/notsobot.py, LINE 1163 "with wand.image.Image(filename=wmm) as wm:"): argument 2: <class 'TypeError'>: wrong type

The bot replied with this message. In the channel. Exposing my file system 🙄

**Comment by TrustyJAID** [comment]
Update your cog, this error was replaced with logging several updates ago. If you're still getting the wand error make sure to read the readme.md in the cog folder as installing this cog is quite extensive.
