### ISSUE TITLE
[Retrigger] Is it possible to have other bots/webhooks fire the triggers?

### ISSUE THREAD

**Issue by DER31K** [TrustyJAID/Trusty-cogs#250]
**Is your feature request related to a problem? Please describe.**
Wondering if this is currently possible to configure - so far I can't get triggers to fire after messages posted by webhooks.

**Describe the solution you'd like**
Hope there is some configuration or setting that already exists to allow webhook messages to fire triggers.

**Describe alternatives you've considered**
I have tried it, also tried enabling specific channels through the allow list.  Nothing could get the webhook to fire the triggers that are fired when I post the same messages directly.

**Comment by TrustyJAID** [comment]
Bots should not listen to other bots. ReTrigger explicitly ignores messages from all other bots so that you don't end up with bots talking to eachother indefinitely hitting rate limit caps.
