### ISSUE TITLE
[RoleTools] A setting to make reactions stay at one

### ISSUE THREAD

**Issue by SkeleBones** [TrustyJAID/Trusty-cogs#252]
**Is your feature request related to a problem? Please describe.**
If someone already has the role from a reaction, they will have to click and unlick it to remove it. 

**Describe the solution you'd like**
A setting to keep reactions at one could help solve this and it would just make the reactions look cleaner in general.

**Comment by TrustyJAID** [comment]
I will not be supporting this option. Clearing the reactions will be heavily rate limited by discord. There is an option to clear them if they get too large. If you want a cleaner look you can wait until discord.py 2.0 is released and Red is updated to support discord.py 2.0 where RoleTools will support buttons and drop down menus which do not have the counter on them.
