### ISSUE TITLE
[Suggestion] [Translate] Add LibreTranslate Support.

### ISSUE THREAD

**Issue by alexvermaning0** [TrustyJAID/Trusty-cogs#259]
**Is your feature request related to a problem? Please describe.**
the problem is that google charges you if you go over 50 translations

**Describe the solution you'd like**
add support for Libre Translate

**Describe alternatives you've considered**
i found that LibreTranslations is a good alternative. and its opensource

**Additional context**
libre translation can be selfhosted but is not required.
the hard part could be detecting the language of the message.

**Comment by TrustyJAID** [comment]
In the past 4 years I have been using google translate on my bot I have never once received a bill for more than $0.01. This includes far more than 50 translations per month on average. I have no intention of supporting another api for translate.
