### ISSUE TITLE
[Starboard] Configuring allowed role and denied channel still allows starring from denied channel

### ISSUE THREAD

**Issue by Injabie3** [TrustyJAID/Trusty-cogs#261]
**Describe the bug**
Not sure if the following behaviour is the new expected behaviour, but when a starboard is configured with an allowed role and a denied channel, messages are still able to be starred from a denied channel.

**To Reproduce**
1. Configure an allowed role.
2. Configure a denied channel.
3. Have people with an allowed role star a message in the denied channel.
4. See the starred message in the denied channel show up in starboard.

**Expected behavior**
The starred message in the denied channel should not show up on the starboard.

**Screenshots**
![image](https://user-images.githubusercontent.com/6710854/134796975-41c6aa41-e396-45cb-937d-efced471cb85.png)
![image](https://user-images.githubusercontent.com/6710854/134796974-ec74dbfb-1577-420d-bf76-faa1e74c8b77.png)

**Additional context**
- Currently running 2.5.3.
- Was working before roles and channels were merged into a single whitelist and single blacklist.

**Comment by Ryonez** [comment]
This happens even without allowed roles. A blocked channel still can have messages stared.
