### ISSUE TITLE
Cleverbot responding with unrelated answers

### ISSUE THREAD

**Issue by IonicEcko** [TrustyJAID/Trusty-cogs#275]
**Describe the bug**
Cleverbot appears to be responding with answers unrelated to the question asked.

**To Reproduce**
1. Assign an API key to Cleverbot (.com)
2. Ask it a question in DM

**Expected behavior**
The response should be one relating to your question.

**Screenshots**
![image](https://user-images.githubusercontent.com/6550614/145537394-8118df2b-7740-4f4c-a09e-adae20cd034e.png)

**Desktop (please complete the following information):**
 - OS: Windows Server 2022
 - Red Version: 3.4.14
 - Python Version: 3.9.7
 - Discord.py: 1.7.3

**Additional context**
Happy to help where I can, no errors in the console or anything with these requests.

**Comment by IonicEcko** [comment]
I just asked 2 more but in a channel using the command instead and the first one looked promising but the second one was not.

![image](https://user-images.githubusercontent.com/6550614/145537932-0df821ea-c69d-410e-8a9d-b8ce57a7b863.png)

**Comment by IonicEcko** [comment]
It almost looks like its trying to respond to the first message in a conversational way (answer then ask a subsequent question?)... in that second example at least.

**Comment by TrustyJAID** [comment]
Have you ever talked to cleverbot before? It's not always able to keep a stable conversation on its own. As such this issue is entirely related to cleverbot itself not the cog. The cog does what it can to try and keep conversations continuing by providing a small portion of the conversation to the API but at the end of the day the issue you're describing is with the API not the cog.

**Comment by IonicEcko** [comment]
Yeah the normal Cleverbot chat works fine... When you ask it if it likes Dinosaurs it says "Yes, I like Dinosaurs" it doesn't respond with something completely unrelated like "Whats your name"

Dissapointing this was closed but thanks anyway.

![image](https://user-images.githubusercontent.com/6550614/146107907-518b5b7b-97c5-43c0-9c7e-6a09ff85f772.png)

**Comment by TrustyJAID** [comment]
This was closed because there's nothing more that I can do in the cog itself. Previous conversation information is sent to the API along with the tokens to get a response so it should be doing as you said but it does not always work that way just with how cleverbot responds in general.
