### ISSUE TITLE
[Destiny] Spams Bot Console

### ISSUE THREAD

**Issue by T14D3** [TrustyJAID/Trusty-cogs#288]
**Describe the bug**
Destiny cog absolutely spams the console with "No manifest found, getting response from API."

**To Reproduce**
Dunno how to reproduce exactly, it just does it for me

**Expected behavior**
Uh, I'd expect it to not spam the console, I guess?

**Screenshots**
![image](https://user-images.githubusercontent.com/73843330/164986895-2a989f24-0973-4241-bdbd-3ca0e1e77519.png)

**Comment by T14D3** [comment]
Oh yeah, and also this 
![image](https://user-images.githubusercontent.com/73843330/164987041-6c8d22f6-d86a-43c8-9ae6-a55d143a19fb.png)

**Comment by TrustyJAID** [comment]
Have you tried using the `[p]destiny manifest` command? That message is to let you know that you're wasting time and API calls and should probably download the manifest to save from doing potentially hundreds of API calls on one command. It will also solve your second error.
