### ISSUE TITLE
stars.py

### ISSUE THREAD

**Issue by Note2Self** [TrustyJAID/Trusty-cogs#3]
With the recent update I'm getting this error 

`File "/app/cogs/starboard.py", line 243, in on_reaction_add
 if has_message is not None:
 UnboundLocalError: local variable 'has_message' referenced before assignment`

**Comment by sean-james** [comment]
You would need to initialize the variable has_message in memory by adding `has_message = None` under line 217 ` async def on_reaction_add(self, reaction, user):`. 

I've added this fix and sent over a pull request to @TrustyJAID .

**Comment by TrustyJAID** [comment]
Fixed this in latest commit.
