### ISSUE TITLE
[V3 Starboard] Reacting to starboard posts

### ISSUE THREAD

**Issue by Zephyrkul** [TrustyJAID/Trusty-cogs#3]
Users reacting to posts in the set starboard channel causes the starboarded messages to be reposted on the starboard, causing a meta-starboard nightmare. Screenshot of an example below.

R. Danny handles star reactions in starboard by considering those stars to be for the original message. That solution or just ignoring stars in the starboard may be useful. Otherwise at least a warning that an admin may want to disable reactions in the starboard channel due to this small difference in behavior.

[![Screenshot of an example](https://gyazo.com/dffd9d1c4e8ac9b34511f80804795db2/raw)](https://gyazo.com/dffd9d1c4e8ac9b34511f80804795db2)

**Comment by TrustyJAID** [comment]
Yes this came back as a result of rewriting the cog to allow multiple starboards. You can blacklist the channel from being watched for the starboard right now to prevent this from happening. I may look at checking if the starboard message is being reacted to and ignoring or even adding to the star message like R.Danny in the near future.

**Comment by TrustyJAID** [comment]
Fixed this in [a10cde7](https://github.com/TrustyJAID/Trusty-cogs/commit/a10cde76f85d7875265a81e307a3a0ba19c88cf8).
