### ISSUE TITLE
Welcomeset not working properly - Doesn't send anything

### ISSUE THREAD

**Issue by Skyridr** [TrustyJAID/Trusty-cogs#31]
I know it's a beta cog, but it appears I can't even get it to work. Set the Whisper / Welcomes on to true, used the default welcome set message `Welcome {0.name} to {1.name}!` and toggled it on (`welcomeset greeting toggle`). Whenever I use a test account to join the guild, nothing happens. I'm not being DM'd at all. Yet I am being DM's by the old V2 welcome cog (temp bot) so it shows I am not blocking any DM's.

If I attempt to use `welcomeset greeting test` also nothing happens. Does this work with DM only set?

Am I doing something wrong here? I'm pretty sure everything should be set up properly.

> Grouped welcomes : False
> Welcomes On : True
> Channel :None
> Goodbyes On : False
> Leaving Channel :None
> Whisper : True
> Bots message : None
> Bots role :None
> Embeds : True

> [10:19 AM] Skyrider: !welcomeset greeting toggle
> [10:19 AM] Mr. Satan: I will now welcome new users to the guild.

> [10:20 AM] Skyrider: !welcomeset greeting list
> [10:20 AM] BOTMr. Satan:
> Welcome messages:
>   `0. Welcome {0.name} to {1.name}!`

With these combined settings, I assume it should be sending "something".

**Comment by dubuhaseul** [comment]
Having the same issue with the following setup, tried without embeds as well.

Welcomes On : True
Channel : #general
Goodbyes On : True
Leaving Channel : #general
Whisper : False
Bots message : None
Bots role :None
Embeds : True

The "test message" it sends after you set the welcomes and goodbyes works perfectly with the embeds.
But doesn't send anything for an actual user event.

**Comment by TrustyJAID** [comment]
I would recommend updating the cog. There is support for RedBot v3.1 which includes backwards compatibility support for 3.0.2.

**Comment by Brandjuh** [comment]
I have the same problem. Worked fine before, just stopped after few welcomes.
