### ISSUE TITLE
Error loading tweets

### ISSUE THREAD

**Issue by nmills3** [TrustyJAID/Trusty-cogs#311]
I just updated Red and the tweets cog and now i get a failed to load message and the following output in the console

[latest.log](https://github.com/TrustyJAID/Trusty-cogs/files/11398417/latest.log)

I'm using docker to host redbot so it's a clean environment with no existing packages. all packages are added by redbot when the container is first created after an update. i've also forced an update to get it to remake the container and reinstall all packages from scratch and the issue still persists.

Also nice to see this repo active again, there are some really good cogs in here

**Comment by TrustyJAID** [comment]
You will need to run `[p]pipinstall async_lru` as the traceback suggests. I have just pushed a fix for installing the cog to let it install the requirements correctly. The warning messages are not something I can do anything about as it's upstream tweepy and I don't know if they've been addressed with the latest release.
