### ISSUE TITLE
[Roletools] Reaction role consistency check

### ISSUE THREAD

**Issue by wohali** [TrustyJAID/Trusty-cogs#313]
## Description

When the bot's offline and someone reacts to a reaction role message, the bot misses the action. Unless that person removes and re-adds the reaction, they can't remove/add the role.

## Suggested solution

A `[p]roletools reaction check <message>` command that scans all of the reactions to that message and makes user state consistent would be great.

Ideally a `[p]roletools reaction check` would check all known message/role pairs.

## Considered alternatives
Right now the only alternatives are manual role assignment or asking users to repeat their work. The problem is knowing when the bot may have fallen offline due to any number of factors.

**Comment by TrustyJAID** [comment]
You would be better off using the new `[p]roletools button` commands and setting up buttons for role assignment than reactions. Discords reactions system is notoriously bad for a variety of reasons and the bot can miss the reaction even if it's online. The new buttons allow the bot to respond directly to the user on successfully applying the role or an error message if it fails. This also removes the need for the user to select and reapply the selection like on reactions. I don't plan to implement something like `[p]roletools reaction check`.
