### ISSUE TITLE
[Roletools] Provide role-count stats as a button toggleable option

### ISSUE THREAD

**Issue by wohali** [TrustyJAID/Trusty-cogs#314]
## Description

In https://github.com/TrustyJAID/Trusty-cogs/issues/313 I asked about doing a consistency check for reaction-based roles. This request was denied, and use of the new buttons feature was suggested, due to the difficulty in dealing with reactions in the Discord API. (Having written my own functionality against reactions, I agree!)

In our community, people use the number of reactions to see how popular a given role-choice is. Using button-based reactions removes this information. And, sadly, Discord doesn't seem to have a good way to surface that information either.

**Describe the solution you'd like**
Provide an option that would show the number of people who have self-assigned a role using a roletools button. Having the number of people with a given role right next to the option to self-assign that role is a good, positive feedback solution.

**Describe alternatives you've considered**
#313 for a start.

Another alternative is a `[p] roletools stats` command, but this would lead to bot spam, when really this is just information a new server member wants to see once - at the time they pick out self-assigned roles.

**Comment by TrustyJAID** [comment]
I don't personally see any reason a user should make a decision on what role they want to assign themselves based on what the community has chosen and this seems like something moderators might want to know and they already can see that through the discord client.

**Comment by TrustyJAID** [comment]
I am more inclined to add statistical information but it would appear on the `[p]roletools viewrole` command and it would just show how many people have that role when the command is run and not show anything about the actual button presses, etc.

**Comment by wohali** [comment]
> I don't personally see any reason a user should make a decision on what role they want to assign themselves based on what the community has chosen and this seems like something moderators might want to know and they already can see that through the discord client.

I help run a gaming community. People self-assign roles that anyone can @-mention to join in a game of that thing. There is a definite herd mentality; based on my analysis, newcomers are more inclined to join groups that have more people in them.

> I am more inclined to add statistical information but it would appear on the [p]roletools viewrole command and it would just show how many people have that role when the command is run and not show anything about the actual button presses, etc.

This is a reasonable alternative, but it's hard to put into a welcome channel and keep updated without making an admin/mod re-issue the command daily. Again, we want everyone to be able to see the counts; with the reactions as we use right now, this is immediately available.

**Comment by TrustyJAID** [comment]
> based on my analysis, newcomers are more inclined to join groups that have more people in them.

I don't believe there's a correlation between the number of people who already have the role and a newcomers decision on this. As you mentioned there's a herd mentality and in gaming specifically people frequently jump between the next newest thing. When a newcomer joins they're going to want to pick games they're interested in or games their friends are interested in which has no relation to the number of people who already have the role in your server. People will naturally trend towards more popular games or perhaps your server has built a reputation for more interest in specific games so newcomers join to be part of those games more than others.

**Comment by wohali** [comment]
Well, regardless of armchair psychology on both our parts, intentionally making it harder to find information that was up front and centre with reaction roles seems an odd choice. If this isn't forthcoming as a feature, we'll stay with reaction roles for now.

**Comment by wohali** [comment]
Thank you @TrustyJAID ! What a pleasant surprise.
