### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by sh4calunegru** [TrustyJAID/Trusty-cogs#323]

**Comment by TrustyJAID** [comment]
I am assuming this is for the Spotify cog. You need to ensure that the redirect URI on the Spotify Dashboard is set to `https://localhost/` as the `[p]spotify set creds` command says to do.

**Comment by sh4calunegru** [comment]
Hi,after i set Spotify Dashboard to https://localhost/ and send command ?spotify playlists list to my bot give me this message 
"Alright I won't interact with spotify for you",after link to authorize i click to be agree but redirect me to a page with "tfis site can be accessed
![Captură de ecran 2023-07-23 084401](https://github.com/TrustyJAID/Trusty-cogs/assets/63900549/42055c32-83a0-4cdf-83be-87cb38ee5edb)

![Captură de ecran 2023-07-23 083809](https://github.com/TrustyJAID/Trusty-cogs/assets/63900549/05da5f35-f862-4c33-a9e7-7f063b12440e)

**Comment by TrustyJAID** [comment]
The bot asks you to DM it the URL. The URL you need to send is the page that says no access.

**Comment by sh4calunegru** [comment]
![Captură de ecran 2023-07-23 084959](https://github.com/TrustyJAID/Trusty-cogs/assets/63900549/a89ca55c-aadd-439e-94f5-7a2502094c84)

**Comment by TrustyJAID** [comment]
Yes, you click that link, on Spotify's page select accept, then you get redirected to `https://localhost/` You need to paste that last locahost URL in DM with the bot. It contains the code necessary to authorize access to Spotify. Only the bot can use this code, it's like a second Password for your account only the bot can use.

**Comment by TrustyJAID** [comment]
In the future, questions like this are better suited on the Cog Support discord server. I have my own channel there. https://discord.gg/GET4DVk

**Comment by sh4calunegru** [comment]
ok man,work ,tnx a loot,have a good day 👍
