### ISSUE TITLE
[Retrigger] allow_multiple not used

### ISSUE THREAD

**Issue by designbyadrian** [TrustyJAID/Trusty-cogs#38]
This was a neat option to combine text responses with reactions.

**Comment by TrustyJAID** [comment]
This was replaced with `[p]retrigger multi` Allowing for blanket multi triggers was something I did not like. However, creating single triggers that do a text response and reactions is still possible although more restrictive to reduce spam on the API.

**Comment by designbyadrian** [comment]
I was hoping for reaction with 0 cool down, and text response with different cool down, but I guess I just have to live without it.
