### ISSUE TITLE
[Backup] Can't backup embed content

### ISSUE THREAD

**Issue by Akubits** [TrustyJAID/Trusty-cogs#56]
After going through the code for Backup as well as the documentation for `discord.py`, I found that `message.content` only saves the content of a regular user-created message. The API grabs message embeds using `message.embeds` instead. In my testing, just using `message.embeds` by itself won't work since apparently the `Embed` object type isn't JSON serializable. I'm no expert at both python and JSON, so I'm opening an issue instead of a pr in case someone else wants to work on it. From what I've been reading, though, a custom encoder might be needed. Again, I'm no expert at this, so I'm just putting up my findings.

**Comment by TrustyJAID** [comment]
After giving this a lot of thought I have decided not to include this. Embeds are typically only created by links or bots and I don't see a purpose in saving bot created messages or embeds for that matter.
