### ISSUE TITLE
[Tweets] Option to filter tweets by hashtag

### ISSUE THREAD

**Issue by Jackenmen** [TrustyJAID/Trusty-cogs#65]
I am thinking of option to additionally filter tweets from the tracked account by hashtag but if it's possible with Streams API then it could also be nice to be able to stream all tweets with the provided hashtag.

**Comment by TrustyJAID** [comment]
While this is technically possible using the streams API the difficult part comes in tracking where to send the tweet on discord. Right now the bot stores all users it's following in a dictionary and then if that user sends a tweet the bot loos up the channels it needs to send that tweet to. Adding hashtag or other keyword streams would mean the bot will receive the tweets but then not quite know where to send it and it also greatly increases the possible number of incoming tweets to deal with potentially leading to rate limit issues on discord. Also in the streams API it's not *just* hashtags that it tracks it can be any keyword.

**Comment by TrustyJAID** [comment]
Well this issue was more feasible and possible on the v2 streaming API which is sadly now too expensive to run so I am closing this issue.
