### ISSUE TITLE
[Tweets] Is the "autotweet" feature supposed to be missing?

### ISSUE THREAD

**Issue by Cabbidachi** [TrustyJAID/Trusty-cogs#68]
I didn't used RED and the Cogs in a while but i can remember that this Cog had an autotweet feature. Now it's gone and i wonder if this is just a bug on my end or if it actually got removed.

**Comment by TrustyJAID** [comment]
`[p]autotweet` is not missing, make sure you have the correct cog installed from this repo as there is another tweets cog that does not have autotweets.
