### ISSUE TITLE
[ServerStats] Avatar command used by another cog

### ISSUE THREAD

**Issue by Skyridr** [TrustyJAID/Trusty-cogs#75]
Just noticed when I attempted to load the cog, I was getting a lovely error.

`discord.errors.ClientException: Command avatar is already registered.`

Turns out, the avatar command is already used by the Avatar cog -> https://github.com/skeith/MayuYukirin/tree/master/avatar

Shouldn't all approved cogs be using different commands to be compatible with one another?  It's a general question btw :D.

**Comment by Dezyox** [comment]
No. 

And if it's a general question, you're best luck to get an answer is to ask on the Red server.

**Comment by TrustyJAID** [comment]
Already answered in the Red Cog server. Generally cog creators may use the same command names as other cogs. In this case my avatar command uses a different converter to find any user with partial name searching and then list them all in a menu. Some people may want just a general user avatar command in which case they can use Yuki's cog although mine comes with a lot of other features that I wanted in the cog.
