### ISSUE TITLE
Avatars images aren't displayed in full size

### ISSUE THREAD

**Issue by Justwinning** [TrustyJAID/Trusty-cogs#85]
Profile pictures or avatars aren't displayed in full size with notsobot cog, instead it shows a small image size (the default discord avatar size 128x128) if possible please enlarge those images when you tag a user or link their profile picture make it display the avatars full size.

Here a example of current results I'm getting when doing commands:
<img width="812" alt="small avatars" src="https://user-images.githubusercontent.com/49597520/71128111-f0e5e300-2205-11ea-9e50-1a7a8041db11.PNG">

**Comment by Jackenmen** [comment]
FYI Trusty, the actual problem was never not passing size (1024 is the default used by d.py so it would still be pretty big), but rather use of regex that strips `?size=1024` part of image URL

**Comment by TrustyJAID** [comment]
Yep I realized that the next day after I fixed it @jack1142. This is now fixed in [b00877f](https://github.com/TrustyJAID/Trusty-cogs/commit/b00877fdf5d873f65219bb749e38bab74a38f443).
