### ISSUE TITLE
[Backup] Option to Restore Channels from File

### ISSUE THREAD

**Issue by LGACode** [TrustyJAID/Trusty-cogs#93]
Add a command that can restore channels from .json files. Bot would create a new channel and output all the stored text into it. Useful for archiving channels to be restored at a later date.

**Comment by TrustyJAID** [comment]
This will not be something I will add to this cog. The number of messages to send and "restore" a channel would inevitably lead to abuse and is considered Spam by discord which is against the bot/dev terms of service.
